[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "8Ju3FWgNEftjMiueY5kFFJvWTM52kJ1sULYWo51BybEm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
